name: publish test docker image
on:
 push:
   branches:
     - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Publish Image
      uses: matootie/github-docker@v3.0.0
      with:
        accessToken: ${{ secrets.TOKEN }}
        tag: |
          latest
          ${{github.sha}}
        imageName: shape-estimation-test
